/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/robotic_hand/scene.gltf -o src/RoboticHand.tsx -r public 
Author: Jackal04 (https://sketchfab.com/Jackal04)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robotic-hand-a1a352baccb243009687ad22a3e4364a
Title: Robotic Hand
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

const customMat = new THREE.MeshPhysicalMaterial({
  color: "#1a1510",
  transmission: 0.9,
  transparent: true,
  opacity: 1,
  roughness: 0.1,
  metalness: 0.4,
  clearcoat: 1
});


type GLTFResult = GLTF & {
  nodes: {
    polySurface19_Thumb_0: THREE.Mesh
    polySurface34_covers_0: THREE.Mesh
    polySurface35_covers_0: THREE.Mesh
    polySurface33_covers_0: THREE.Mesh
    polySurface28_Thumb_0: THREE.Mesh
    pCube43_covers_0: THREE.Mesh
    polySurface1_Thumb_0: THREE.Mesh
    polySurface17_Index_0: THREE.Mesh
    pCube20_Index_0: THREE.Mesh
    pCube19_Index_0: THREE.Mesh
    polySurface30_Middle_0: THREE.Mesh
    polySurface12_Middle_0: THREE.Mesh
    pCube21_Middle_0: THREE.Mesh
    polySurface31_Ring_0: THREE.Mesh
    pCube23_Ring_0: THREE.Mesh
    pCube22_Ring_0: THREE.Mesh
    polySurface32_Pinky_0: THREE.Mesh
    pCube25_Pinky_0: THREE.Mesh
    pCube24_Pinky_0: THREE.Mesh
    polySurface39_covers_0: THREE.Mesh
    pCube42_covers_0: THREE.Mesh
    pCube41_covers_0: THREE.Mesh
    pCube26_covers_0: THREE.Mesh
    pCube37_covers_0: THREE.Mesh
    pPipe9_covers_0: THREE.Mesh
    pCube36_covers_0: THREE.Mesh
    pPipe10_covers_0: THREE.Mesh
    pCube35_covers_0: THREE.Mesh
    pPipe11_covers_0: THREE.Mesh
    pCube34_covers_0: THREE.Mesh
    pPipe12_covers_0: THREE.Mesh
    pSphere5_Hand_0: THREE.Mesh
    pCube27_covers_0: THREE.Mesh
    pPipe13_covers_0: THREE.Mesh
    pPipe14_covers_0: THREE.Mesh
    polySurface3_Hand_0: THREE.Mesh
    pSphere2_Hand_0: THREE.Mesh
    pPipe2_covers_0: THREE.Mesh
    pPipe2_lambert1_0: THREE.Mesh
    pPipe8_covers_0: THREE.Mesh
  }
  materials: {
    Thumb: THREE.MeshStandardMaterial
    covers: THREE.MeshStandardMaterial
    Index: THREE.MeshStandardMaterial
    Middle: THREE.MeshStandardMaterial
    Ring: THREE.MeshStandardMaterial
    Pinky: THREE.MeshStandardMaterial
    Hand: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export default function RoboticHand(props: React.JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF(import.meta.env.BASE_URL + 'robotic_hand/scene.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0.032, 0, 0.094]} rotation={[0, 0.124, 0]}>
          <mesh geometry={nodes.pPipe2_covers_0.geometry} material={customMat} />
          <mesh geometry={nodes.pPipe2_lambert1_0.geometry} material={customMat} />
        </group>
        <mesh geometry={nodes.pSphere2_Hand_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface3_Hand_0.geometry} material={customMat} />
        <mesh geometry={nodes.pSphere5_Hand_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface1_Thumb_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface28_Thumb_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface19_Thumb_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface33_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface34_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface35_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube43_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube19_Index_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube20_Index_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface17_Index_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube21_Middle_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface12_Middle_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface30_Middle_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube22_Ring_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube23_Ring_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface31_Ring_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube24_Pinky_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube25_Pinky_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface32_Pinky_0.geometry} material={customMat} />
        <mesh geometry={nodes.polySurface39_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube42_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube41_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube26_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube37_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pPipe9_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube36_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pPipe10_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube35_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pPipe11_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube34_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pPipe12_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pCube27_covers_0.geometry} material={customMat} />
        <mesh geometry={nodes.pPipe13_covers_0.geometry} material={customMat} position={[0.042, -0.012, -0.011]} rotation={[0, 0.116, 0]} />
        <mesh geometry={nodes.pPipe14_covers_0.geometry} material={customMat} position={[0.044, 0, -0.02]} rotation={[0, 0.116, 0]} />
        <mesh geometry={nodes.pPipe8_covers_0.geometry} material={customMat} position={[0.03, 0, -0.048]} rotation={[0, 0.103, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'robotic_hand/scene.gltf')
